CREATE TABLE categories (id INT(2) PRIMARY KEY AUTO_INCREMENT, name VARCHAR(20)
NOT NULL);
CREATE TABLE stock (id INT(7) PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50)
NOT NULL, quantity INT(7) DEFAULT 0, category INT(2) NOT NULL, unit_price INT(7),
image VARCHAR(15), FOREIGN KEY (category) REFERENCES categories(id));
CREATE TABLE users (id INT(7) PRIMARY KEY AUTO_INCREMENT, email VARCHAR(50),
username VARCHAR(50), password TEXT, admin TINYINT DEFAULT 0);
CREATE TABLE orders (id INT(7) PRIMARY KEY AUTO_INCREMENT, user_id INT(7),
items TEXT, status INT(1));
